version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    #  - image: arm32v7/gcc:latest
      
    working_directory: /mio
    steps:
      - checkout
      
      #sudo apt-get install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc-arm-linux-gnueabihf'
     # - run: apt-get install gcc-arm-linux-gnueabihf
      - run: g++ -o main Test_endian.c -std=c++11
      - run: pwd
      - run: ls -la
      - run: ./main
      - store_artifacts:
            path: /mio/main
            destination: test_endian

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
