version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
   
    environment:
          GO111MODULE: "on"
      
    working_directory: /mio
    
    steps:
      - checkout
      - run:
          name: Installing ghr 
          command: go get github.com/tcnksm/ghr
      
      # - run: apt-get update && apt-get install -y golang
      - run:
          name: Installing GCC for ARM
          command: 'apt-get update && apt-get install -y gcc-arm-linux-gnueabihf'
      
      - run: g++ -o main Test_endian.c -std=c++11
      - run: arm-linux-gnueabihf-gcc -o main_arm Test_endian.c -std=c++11
  
      - run: find . -name ghr
      - run: mkdir ./artifacts
      - run: cp main* ./artifacts
      
      #- run: VERSION=$(main_arm --version)
      - run: VERSION="1.0.0"
      - run: /root/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      

      - store_artifacts:
            path: /mio/main
            destination: test_endian
      - store_artifacts:
            path: /mio/main_arm
            destination: test_endian_arm
   

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
