version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    working_directory: /mio
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: g++ -o main Test_endian.c -std=c++11
      - run: pwd
      - run: ls -la
      - run: ./main
      - run: Write-Host 'Hello da lukg'
      - store_artifacts:
            path: /mio/main
            destination: ExeFile

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
